### ISSUE TITLE
迁移老项目代码

### ISSUE THREAD

**Issue by xhzq233** [xhzq233/pivot_chat#5]
项目地址：
[旧项目地址](https://github.com/xhzq233/chat_box)
可以迁移的：
- 大部分逻辑
- 考虑到现在设计完成度较低，可以先迁移一部分UI

困难：
考虑到老项目有一些使用的框架不一样，并且是@xhzq233造的屎，就由@xhzq233自己完成

**Comment by Godlowd** [comment]
这个还是别让他们来搞了，自己搞估计都够呛。更别说没接触过项目的新人

**Comment by xhzq233** [comment]
> 这个还是别让他们来搞了，自己搞估计都够呛。更别说没接触过项目的新人

你是不是没看我assign谁了😠

**Comment by Godlowd** [comment]
噢竟然还有assignee的
