### ISSUE TITLE
[workflow]: releasing automation

### ISSUE THREAD

**Issue by xhzq233** [xhzq233/pivot_chat#7]
## Proposal
自动化Flutter构建与发布，预期支持平台：
- macOS [x86, arm64]
- iOS
- android [x86/64, arm64, arm32]
- ubuntu

**Comment by Godlowd** [comment]
没必要支持这么多平台吧，支持最常见的安卓arm64 32和iOS就行了我觉得。而且iOS他们不一定都有测试环境

**Comment by xhzq233** [comment]
> 预期

**Comment by xhzq233** [comment]
> 没必要支持这么多平台吧，支持最常见的安卓arm64 32和iOS就行了我觉得。而且iOS他们不一定都有测试环境

预期
